export const GET_POST = 'GET_POST'
export const UPDATE_POST = 'UPDATE_POST'
export const ERROR_POST = 'ERROR_POST'
export const LOADING_POST = 'LOADING_POST'
export const RESET_POST = 'RESET_POST'
export const SUCCESS_CREATE_POST = 'SUCCESS_CREATE_POST'